version: '3.9'
services:
  terra-stats-api:
    build: terra-stats-api
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
  terra-account-stats-bot:
    build: terra-account-stats-bot
    ports:
      - "9090:8080"
      - "5005:5005"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
