openapi: 3.0.3
info:
  title: Terra Stats OpenAPI contract
  description: Terra Stats OpenAPI contract
  version: 1.0.0
paths:
  /swaps/{terra-address}:
    get:
      summary: get swaps for given coin
      description: get swaps for given coin
      operationId: getSwaps
      tags:
        - /swaps
      parameters:
        - name: terra-address
          in: path
          schema:
            type: string
          required: true
        - name: hide
          in: query
          schema:
            type: array
            items:
              type: string
          required: false

      responses:
        200:
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BuySellSwapsPerCoin'
        500:
          description: internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    SwapEntry:
      type: object
      properties:
        id:
          type: string
        price:
          type: number
        amount:
          type: number
    Swaps:
      type: object
      properties:
        swaps:
          type: array
          items:
            $ref: '#/components/schemas/SwapEntry'
    BuySellSwaps:
      type: object
      properties:
        coin:
          type: string
        buy:
          $ref: '#/components/schemas/Swaps'
        sell:
          $ref: '#/components/schemas/Swaps'
    BuySellSwapsPerCoin:
      type: object
      properties:
        entries:
          type: array
          items:
            $ref: '#/components/schemas/BuySellSwaps'
    Error:
      type: object