openapi: 3.0.3
info:
  title: Terra Stats OpenAPI contract
  description: Terra Stats OpenAPI contract
  version: 1.0.0
paths:
  /average-buy-sell/{token}/{terra-address}:
    get:
      summary: get the average prices for given token
      description: get the average prices for given token
      operationId: getAverageBuySell
      tags:
        - /average-buy-sell
      parameters:
        - name: token
          in: path
          schema:
            type: string
          required: true
        - name: terra-address
          in: path
          schema:
            type: string
          required: true
      responses:
        200:
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Stats'
        500:
          description: internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    Stats:
      type: object
      properties:
        buy-map:
          type: object
        sell-map:
          type: object
    Error:
      type: object